### ISSUE TITLE
Documentation Issue - Soon to be deprecated command

### ISSUE THREAD

**Issue by evanhowington** [Electrum-RVN-SIG/electrumx-ravencoin#10]
With respect to the "ElectrumX Ravencoin How-To.md" file.

The following line:
> Now double-check that the rvn node is running and up-to-date with the blocks:**./raven/bin/raven-cli getinfo** if that looks ok you can start the electrumx server: **systemctl start electrumx** 

The "raven-cli getinfo" command will be deprecated soon.  Here is the server response. 
>"deprecation-warning": "WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16"

**Comment by kralverde** [comment]
Updated in https://github.com/Electrum-RVN-SIG/electrumx-ravencoin/commit/b2822bb282b354e87dc332bd3ebc73091586ec51
