### ISSUE TITLE
Asset id counter corrupted

### ISSUE THREAD

**Issue by mahen57** [Electrum-RVN-SIG/electrumx-ravencoin#13]
Electrumx seemed to be running fine after setup, then encountered this:
---
Jul 11 14:13:30 electrumx-V2204 electrumx_server[8391]: INFO:BlockProcessor:UTXOs 1,633MB Assets 0MB hist 171MB
Jul 11 14:13:30 electrumx-V2204 electrumx_server[8391]: INFO:BlockProcessor:height 1,878,255 of 2,881,487 0000000000008730679>
Jul 11 14:13:33 electrumx-V2204 electrumx_server[8391]: INFO:History:flushed history in 2.7s for 506,458 addrs
Jul 11 14:13:33 electrumx-V2204 electrumx_server[8391]: INFO:DB:2 restricted assets modified, 0 retricted asset freezes, 48 a>
Jul 11 14:13:33 electrumx-V2204 electrumx_server[8391]: INFO:DB:1,006 assets' metadata created, 52 assets' metadata reissued,>
Jul 11 14:13:46 electrumx-V2204 systemd[1]: electrumx.service: Main process exited, code=killed, status=9/KILL
Jul 11 14:13:46 electrumx-V2204 systemd[1]: electrumx.service: Failed with result 'signal'.
Jul 11 16:20:49 electrumx-V2204 systemd[1]: Started Electrumx.
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:electrumx:ElectrumX server starting
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:electrumx:logging level: INFO
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:Python version: 3.10.6 (main, May 29 2023, 11:10:38) >
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:software version: ElectrumX Ravencoin 1.11
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:aiorpcX version: 0.22.1
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:supported protocol versions: 1.4-1.11
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:event loop policy: <uvloop.EventLoopPolicy object at >
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:reorg limit is 60 blocks
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Daemon:daemon #1 at 127.0.0.1:8766/ (current)
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:DB:switching current directory to /home/electrumx/electrumx_db
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:DB:using leveldb for DB backend
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:DB:opened UTXO DB (for sync: True)
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: WARNING:DB:asset id counter corrupted, attempting to recover
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:SessionManager:stopping servers
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:SessionManager:closing connections...
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:SessionManager:connections closed
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:shutting down
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: INFO:Controller:shutdown complete
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: ERROR:electrumx:ElectrumX server terminated abnormally
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: Traceback (most recent call last):
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx_server", line 35, in main
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     asyncio.run(controller.run())
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     return loop.run_until_complete(main)
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_co>
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/lib/server_base.py", line>
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     await server_task
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/lib/server_base.py", line>
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     await self.serve(shutdown_event)
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/server/controller.py", li>
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     task.result()
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/server/block_processor.py>
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     self.state = OnDiskBlock.state = (await self.db.open_for_sync()).>
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/server/db.py", line 205, >
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     return await self._open_dbs(True, False)
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/server/db.py", line 183, >
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     self.read_utxo_state()
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:   File "/home/electrumx/electrumx/electrumx/server/db.py", line 868, >
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]:     last_asset_id += 1
Jul 11 16:20:50 electrumx-V2204 electrumx_server[9089]: TypeError: can't concat int to bytes
Jul 11 16:20:50 electrumx-V2204 systemd[1]: electrumx.service: Deactivated successfully.
---
The ravend service is running fine.

**Comment by kralverde** [comment]
Sorry for the late reply, it seems you had caught me in the middle of an update. If you haven't done so, retrying from the latest commit should work

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrumx-ravencoin/releases/tag/v1.11.0
